export default {
  ACTION_GET_MOVIES: "ACTION_GET_MOVIES",
  ACTION_GET_GENRES: "ACTION_GET_GENRES",
  MUTATION_MOVIES: "MUTATION_MOVIES",
  MUTATION_GENRES: "MUTATION_GENRES",
  GET_MOVIES: "GET_MOVIES",
  GET_GENRES: "GET_GENRES",
  GET_GENRE_BY_IDS: "GET_GENRE_BY_IDS"
};
